export const people = [
  {
    id: 0,
    password: 'qwerty',
    e_mail: 'master@mail.ru',
    master_name: 'Людмила Заглубоцкая',
    is_master: true,
    skills: 'Мастер по маникюру. Мастер по педикюру',
    img:
      'https://i.pinimg.com/736x/f8/6e/76/f86e76f6ffef4f295dbaafe2428195b5.jpg',
    phone_number: '+375251234567',
    phone_number_second: '+375297654321',
    city: 'Минск',
    address: 'ул. Советская, д.123',
    metro: 'Купаловская',
    work_address: 'ул. Неманская, д.11',
    website: 'bla_bla.ru',
    about_me:
      'Всех приветствую в своём профиле. Я Светлана - сертифицированный мастер ногтевого сервиса. Закончила курс по специальности “Мастер по маникюру” и “Мастер по педикюру”. Слежу за новыми тенденциями и новинками.',
    my_services: [
      {
        name: 'Европейский маникюр',
        how_mach: '750',
        how_long: 1,
        description:
          'Не обрезной маникюр, в результате которого кутикула удаляется при помощи шлифовки специальным аппаратом с различными видами насадок.',
      },
      {
        name: 'Азиатский маникюр',
        how_mach: '1100',
        how_long: 1,
        description:
          'Не обрезной маникюр, в результате которого кутикула удаляется при помощи шлифовки специальным аппаратом с различными видами насадок.',
      },
      {
        name: 'Какой-то маникюр',
        how_mach: '900',
        how_long: 2,
        description: 'Описание услуги',
      },
      {
        name: 'Ремонт ногтя',
        how_mach: '750',
        how_long: 2,
        description:
          'Не обрезной маникюр, в результате которого кутикула удаляется при помощи шлифовки специальным аппаратом с различными видами насадок.',
      },
    ],
    my_notes: [
      {
        client_id: 1,
        day: '25',
        month: '1',
        year: '2020',
        time: '10:00',
        is_active: true,
        is_archive: false,
        photo: [
          'https://sun9-59.userapi.com/c858020/v858020506/ff312/MDUjRGHDhbQ.jpg?ava=1',
          'https://i.pinimg.com/474x/9a/57/f0/9a57f0e84191e278d840a5536ebab34c.jpg',
          'https://nail-design-photos.ru/wp-content/uploads/2017/01/nyudovyj-manikyur-3.jpg',
        ],
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1.5,
          },
        ],
      },
      {
        client_id: 1,
        day: '26',
        month: '1',
        year: '2020',
        time: '10:00',
        is_active: false,
        is_archive: true,
        photo: [
          'https://sun9-59.userapi.com/c858020/v858020506/ff312/MDUjRGHDhbQ.jpg?ava=1',
          'https://nail-design-photos.ru/wp-content/uploads/2017/01/nyudovyj-manikyur-3.jpg',
        ],
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
        ],
      },
    ],
    work_time: [
      {
        name: 'понедельник',
        is_holiday: false,
        start_time: '10:30',
        end_time: '15:00',
        all_time: ['10:15', '11:00', '13:45'],
      },
      {
        name: 'вторник',
        is_holiday: false,
        start_time: '15:00',
        end_time: '',
        all_time: ['10:15', '19:00'],
      },
      {
        name: 'среда',
        is_holiday: false,
        start_time: '',
        end_time: '',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'четверг',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'пятница',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'суббота',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'воскресенье',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
    ],
  },
  {
    id: 4,
    password: 'qwerty',
    e_mail: 'master4@mail.ru',
    master_name: 'Иван Иванов',
    is_master: true,
    img: 'https://i.ytimg.com/vi/1nSflg2vHdg/hqdefault.jpg',
    phone_number: '+375251234567',
    phone_number_second: '+375297654321',
    city: 'Минск',

    address: 'ул. Ангарская, д.1',
    website: 'bla_bla3.ru',
    about_me:
      'Всех приветствую в своём профиле. Я Иван - сертифицированный мастер ногтевого сервиса. Закончила курс по специальности “Мастер по маникюру” и “Мастер по педикюру”. Слежу за новыми тенденциями и новинками.',
    my_services: [
      {
        name: 'Европейский маникюр',
        how_mach: '750',
        how_long: 1,
      },
      {
        name: 'Азиатский маникюр',
        how_mach: '1100',
        how_long: 1,
      },
      {
        name: 'Австралийский маникюр',
        how_mach: '750',
        how_long: 1,
      },
      {
        name: 'Африканский маникюр',
        how_mach: '1100',
        how_long: 1,
      },
    ],
    my_notes: [
      {
        client_id: 1,
        day: '25',
        month: '4',
        year: '2020',
        time: '10:00',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1,
          },
        ],
      },
    ],
    work_time: [
      {
        name: 'понедельник',
        is_holiday: false,
        start_time: '10:30',
        end_time: '15:00',
        all_time: ['10:15', '11:00', '13:45'],
      },
      {
        name: 'вторник',
        is_holiday: false,
        start_time: '15:00',
        end_time: '',
        all_time: ['10:15', '19:00'],
      },
      {
        name: 'среда',
        is_holiday: false,
        start_time: '',
        end_time: '',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'четверг',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'пятница',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'суббота',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'воскресенье',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
    ],
  },
  {
    id: 2,
    password: 'qwerty',
    e_mail: 'master1@mail.ru',
    master_name: 'Татьяна Петрова',
    is_master: true,
    img:
      'https://womans.ws/wp-content/uploads/2019/10/1523527373_44-1068x1068.jpg',
    phone_number: '+375251234567',
    phone_number_second: '+375297654321',
    city: 'Москва',
    address: 'пр-т. Независимости д.64',
    website: 'bla_bla.ru',
    about_me:
      'Всех приветствую в своём профиле. Я Светлана - сертифицированный мастер ногтевого сервиса. Закончила курс по специальности “Мастер по маникюру” и “Мастер по педикюру”. Слежу за новыми тенденциями и новинками.',
    my_services: [
      {
        name: 'Европейский маникюр',
        how_mach: '750',
        how_long: 1,
      },
      {
        name: 'Азиатский маникюр',
        how_mach: '1100',
        how_long: 1,
      },
      ,
      {
        name: 'Еще какой-то маникюр',
        how_mach: '1100',
        how_long: 1,
      },
    ],
    my_notes: [
      {
        client_id: 1,
        day: '25',
        month: '4',
        year: '2020',
        time: '10:00',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1,
          },
        ],
      },
      {
        client_id: 1,
        day: '5',
        month: '5',
        year: '2020',
        time: '10:00',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1,
          },
        ],
      },
    ],
    work_time: [
      {
        name: 'понедельник',
        is_holiday: false,
        start_time: '10:30',
        end_time: '15:00',
        all_time: ['10:15', '11:00', '13:45'],
      },
      {
        name: 'вторник',
        is_holiday: false,
        start_time: '15:00',
        end_time: '',
        all_time: ['10:15', '19:00'],
      },
      {
        name: 'среда',
        is_holiday: false,
        start_time: '',
        end_time: '',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'четверг',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'пятница',
        is_holiday: false,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'суббота',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
      {
        name: 'воскресенье',
        is_holiday: true,
        start_time: '10:00',
        end_time: '20:00',
        all_time: ['10:15', '11:00', '13:45', '19:00'],
      },
    ],
  },
  {
    id: 1,
    password: 'qwerty',
    e_mail: 'client@mail.ru',
    client_name: 'Иванова Анна',
    is_client: true,
    phone_number: '+375254568578',
    city: 'Минск',
    metro: 'Якуба Коласа',
    address: 'Ленина д.14',
    my_notes: [
      {
        master_id: 0,
        day: '25',
        month: '1',
        year: '2020',
        time: '10:45',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 2,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1,
          },
        ],
      },
      {
        master_id: 2,
        day: '30',
        month: '1',
        year: '2020',
        time: '10:45',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 3,
          },
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 1,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    password: 'qwerty',
    e_mail: 'client3@mail.ru',
    client_name: 'Соколова Анна',
    is_client: true,
    phone_number: '+375254568578',
    city: 'Киев',
    address: 'Комсомольская д.55',
    my_notes: [
      {
        master_id: 0,
        day: '24',
        month: '2',
        year: '2020',
        time: '10:45',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Европейский маникюр',
            how_mach: '300',
            how_long: 1,
          },
        ],
      },
      {
        master_id: 2,
        day: '23',
        month: '01',
        year: '2020',
        time: '10:00',
        is_active: true,
        is_archive: false,
        services: [
          {
            name: 'Реставрация ногтя',
            how_mach: '1250',
            how_long: 2,
          },
        ],
      },
    ],
  },
];
