require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'salon' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'salonTests' do
    inherit! :complete
  end
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'salon-tvOS' do


  target 'salon-tvOSTests' do
    inherit! :search_paths
  end
end